trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'Install dependencies'

- script: npm run test
  displayName: 'Run unit tests'

- script: npm run lint
  displayName: 'Static code analysis'

- script: npm run coverage
  displayName: 'Code coverage'

- script: |
    # Build and push Docker image
    docker build -t node-test:$(Build.BuildId) .
    docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
    docker push $(DOCKER_USERNAME)/node-test:$(Build.BuildId)
  displayName: 'Docker Build & Push'

- script: |
    # Vulnerability Scan
    # Install Trivy
    wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).deb
    sudo dpkg -i trivy_$(uname -s)_$(uname -m).deb

    # Run vulnerability scan with Trivy
    trivy image --severity HIGH,CRITICAL $(DOCKER_USERNAME)/node-test:$(Build.BuildId)
  displayName: 'Vulnerability Scan'


